"""init

Revision ID: 39f912fd54f2
Revises: 
Create Date: 2026-06-25 12:30:52.129350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39f912fd54f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('ROLE_ADMIN', 'ROLE_ADJUSTER', 'ROLE_BROKER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_number', sa.String(length=50), nullable=False),
    sa.Column('policy_number', sa.String(length=50), nullable=False),
    sa.Column('claimant_id', sa.UUID(), nullable=False),
    sa.Column('broker_id', sa.UUID(), nullable=True),
    sa.Column('claim_type', sa.Enum('auto', 'health', 'property', 'life', name='claimtype'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'under_review', 'ai_processing', 'human_review', 'approved', 'rejected', 'closed', name='claimstatus'), nullable=False),
    sa.Column('incident_date', sa.DateTime(), nullable=False),
    sa.Column('incident_location', sa.String(length=500), nullable=True),
    sa.Column('incident_description', sa.Text(), nullable=True),
    sa.Column('claimed_amount', sa.Float(), nullable=True),
    sa.Column('approved_amount', sa.Float(), nullable=True),
    sa.Column('ai_decision', sa.String(length=50), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('ai_metadata', sa.JSON(), nullable=True),
    sa.Column('adjuster_id', sa.UUID(), nullable=True),
    sa.Column('adjuster_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adjuster_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['broker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['claimant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_claim_number'), 'claims', ['claim_number'], unique=True)
    op.create_index(op.f('ix_claims_policy_number'), 'claims', ['policy_number'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_number', sa.String(length=50), nullable=False),
    sa.Column('holder_id', sa.UUID(), nullable=False),
    sa.Column('broker_id', sa.UUID(), nullable=True),
    sa.Column('policy_type', sa.String(length=50), nullable=False),
    sa.Column('insurer_name', sa.String(length=255), nullable=False),
    sa.Column('premium', sa.Float(), nullable=True),
    sa.Column('coverage_amount', sa.Float(), nullable=True),
    sa.Column('deductible', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('coverage_details', sa.JSON(), nullable=True),
    sa.Column('exclusions', sa.Text(), nullable=True),
    sa.Column('terms_document_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['holder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_policy_number'), 'policies', ['policy_number'], unique=True)
    op.create_table('claim_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Float(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_documents')
    op.drop_index(op.f('ix_policies_policy_number'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_claims_policy_number'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_number'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
